openapi: 3.0.3
info:
  title: Document management
  description: Document management
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /documents:
    post:
      summary: Create a document
      operationId: createDocument
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '400':
          $ref: '#/components/schemas/ProblemJson'
        '201':
          description: Created
          headers:
            location:
              schema:
                type: string
                description: Location of the created document

components:
  schemas:
    ProblemJson:
      properties:
        type:
          type: string
          description: URI reference RFC 3986
        title:
          type: string
          description: A short, human-readable summary of the problem type
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          description: URI reference RFC 3986
        stacktrace:
          type: string
          description: Stacktrace
        cause:
          type: string
          description: Cause