openapi: 3.0.3
info:
  title: Document management
  description: Document management
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /documents:
    post:
      summary: Create a document
      operationId: createDocument
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '400':
          description: In case of validation errors, such as missing required fields, file size too large, etc.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '201':
          description: Created
          headers:
            location:
              schema:
                type: string
                description: Location of the created document

components:
  schemas:
    Error:
      properties:
        type:
          type: string
          description: URI reference RFC 3986
        title:
          type: string
          description: A short, human-readable summary of the problem type
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          description: URI reference RFC 3986
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth2/authorize
          tokenUrl: https://example.com/oauth2/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants read and write access to administrative information