openapi: 3.0.3
info:
  title: Document management
  description: Document management
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /documents:
    get:
      summary: Retrieves user documents
      operationId: getDocuments
      security:
        - oauth2:
            - read
      parameters:
        - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
    post:
      summary: Create a document
      operationId: createDocument
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Created
          headers:
            location:
              schema:
                type: string
                description: Location of the created document

        '413':
          description: File too large
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                fileTooLarge:
                  value:
                    type: '/errors/file-too-large'
                    title: 'File too large'
                    status: 413
                    detail: 'The file is too large.'
                    instance: 'SOME_UUID_HERE'

        '400':
          description: In case of validation errors, such as missing required fields, file size too large, etc.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                missingDescription:
                  value:
                    type: '/errors/missing-required-field'
                    title: 'Missing description field'
                    status: 400
                    detail: 'The description is required.'
                    instance: 'SOME_UUID_HERE'
                missingTags:
                  value:
                    type: '/errors/missing-required-field'
                    title: 'Missing tags'
                    status: 400
                    detail: 'The tags are required.'
                    instance: 'SOME_UUID_HERE'
components:
  parameters:
    Sort:
      name: sort
      in: query
      description: |
        Sort by field
        
        If the sorting field does not exist, it will be ignored. If the field is prefixed with a minus sign, the sorting will be descending. 
        If the field is prefixed with a plus sign, the sorting will be ascending. If the field is not prefixed with a minus or plus sign, the sorting will be ascending. 
        Multiple fields can be specified, separated by commas
      schema:
        type: string
      example: `-createdAt,description`
  schemas:
    Document:
      type: object
      properties:
        id:
          type: string
          description: Document ID
        description:
          type: string
          description: Document description
        tags:
          type: array
          items:
            type: string
          description: Document tags
        createdAt:
          type: string
          format: date-time
          description: Document creation date
        updatedAt:
          type: string
          format: date-time
          description: Document update date
    Error:
      properties:
        type:
          type: string
          description: URI reference RFC 3986
        title:
          type: string
          description: A short, human-readable summary of the problem type
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          description: URI reference RFC 3986
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth2/authorize
          tokenUrl: https://example.com/oauth2/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants read and write access to administrative information